# Generated by Django 5.0.1 on 2024-05-08 13:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('apiKey', models.CharField(blank=True, max_length=1500)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athleteName', models.CharField(max_length=100)),
                ('athleteId', models.IntegerField()),
                ('imageUrl', models.CharField(max_length=10000)),
                ('flag', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(blank=True, max_length=100)),
                ('player2', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SolidityToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tokenValue', models.IntegerField()),
                ('metadata', models.CharField(max_length=10000)),
                ('tokenId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=10000)),
                ('transactionName', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.CharField(max_length=100)),
                ('contractType', models.CharField(max_length=100)),
                ('contractAddress', models.CharField(blank=True, max_length=100)),
                ('contractId', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experienceId', models.IntegerField()),
                ('experienceName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('imageUrl', models.CharField(max_length=10000)),
                ('flag', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lumxs.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='LumxToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maxSupply', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=10000)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lumxs.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletAddress', models.CharField(blank=True, max_length=100)),
                ('walletId', models.CharField(blank=True, max_length=100)),
                ('walletTokens', models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
