[profile.default]
solc_version = "0.8.20" ## versao um pouco mais antiga que o normal quando for inicializar o projeto no foundry
src = "src"
out = "out"
libs = ["lib"]
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
bytecode_hash = "none"
auto_detect_solc = true
fuzz = { runs = 1_000 }
gas_reports = ["*"]
script = "script"
test = "test"
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
]
optimizer = true
optimizer_runs = 50
#optimizer_runs = 10_000

evm_version = "paris" ##importante colocar na versao mais antiga para funcionar o deploy
# See https://www.evmdiff.com/features?name=PUSH0&kind=opcode

[invariant]
#fail_on_revert = true
# os testes vao falhar por deixar em true

[etherscan]
 # polygon = { key = "${API_KEY_POLYGONSCAN}" }
  sepolia = { key = "${ETHERSCAN_RPC_URL}" }
 # scroll  = { key = "${API_KEY_SCROLLCAN}" }
 # chiliz  = { key = "${API_KEY_CHILIZSCAN}" }

[rpc_endpoints]
  mumbai = "${POLYGON_MUMBAI_RPC_URL}"
  amoy = "${POLYGON_AMOY_RPC_URL}"
  sepolia = "${ETHER_SEPOLIA_RPC_URL}"
  optimism = "${OPTIMISM_SEPOLIA_RPC_URL}"
  bvm = "${NOS_BVM_TEST_RPC_URL}"
  scroll = "${SCROLL_TEST_RPC_URL}"
  chiliz = "${CHILIZ_TEST_RPC_URL}"